---
title: "Opcje_final"
author: "B.Stachewicz K.Dusińska B.Machnacki"
date: "8 November 2015"
output: html_document
---


###1. Opcja - definicja i opis instrumentu
***

####1.1. Definicja  
**Opcja** jest to jeden z podstawowych instrumentów pochodnych.  

Przed poznaniem szczegółów warto wiedzieć, że:  
  
+**opcje nie są trudne**   
Wbrew ogólnej opinii, inwestowanie w opcje nie musi być trudne.   
Na rynku tym można tworzyć strategie dla doświadczonych inwestorów, ale również dla  
początkujących. Najprostszym sposobem inwestowania w opcje jest kupowanie opcji.   
Ten sposób inwestowania jest prosty oraz charakteryzuje się możliwością zrealizowania bardzo dużych zysków.  
  
+**można osiągnąć duże stopy zwrotu**  
Kupując opcje, można osiągnąć bardzo duże zyski (na żadnej innej strategii opcyjnej nie można zarobić więcej).   
Dlaczego tak się dzieje? Ponieważ kurs opcji charakteryzuje się bardzo dużą zmiennością, co oznacza, że w przypadku wzrostu wartości instrumentu bazowego  
kurs opcji kupna wzrośnie dużo więcej. Dlatego inwestowanie w opcje jest znacznie bardziej opłacalne niż w akcje.  
  
+**masz ograniczone straty**  
Opcja to instrument, na którym można dużo więcej zarobić niż stracić.  
Na rynku nie ma drugiego takiego instrumentu. Co ważne, przy opcjach od początku wiadomo, ile maksymalnie można stracić.  
  
+**nie ma depozytu zabezpieczającego**  
Inwestorzy handlujący kontraktami terminowymi wiedzą, z czym wiąże się depozyt zabezpieczający:   dopłacanie pieniędzy, konieczność zamykania stratnych pozycji, coraz większe straty.  

   
  
Ogólnie opisując, instrument ten pozwala nabyć nam prawo zakupu (bądź sprzedaży) określonej ilości dobra po ustalonej cenie w określonym z góry terminie.
Dzięki czemu możemy zabezpieczyć się przed ryzykiem.   
  
Przytaczając pierwszy lepszy przykład z brzegu, twórca oprogramowania R może kupić opcje sprzedaży  
100 licencji oprogramowania po cenie 2 zł za sztukę ( i tak na wolnym rynku nikt by więcej nie dał za ten wyborny program)  
w terminie 24-12-2015. A niech ma na wigilijnego karpia.  
  
Jak wcześniej wspominaliśmy, dla opcji muszą być określone 3 wartości:  
+**ilość** instrumentu podstawowego w transakcji kupna lub sprzedaży  
+**ustalona cena**, po jakiej ma prawo być dokonana transakcja, cena ta zwana jest ceną wykonania
lub ceną realizacji  
+**termin**, do którego można kupić lub sprzedać instrument podstawowy, tzn. wykonać opcję  

**Instrumentem podstawowym** najczęściej są:  
+papiery wartościowe  
+indeksy giełdowe  
+stopy procentowe  
+waluty  

Występują dwa podstawowe rodzaje opcji:  
+**opcja kupna** (nazywana również opcją call);  
+**opcja sprzedaży** (nazywana również opcją put)

Wyróżniamy jeszcze podział opcji ze względu na możliwość ich wykonania:  
+**opcja europejska**- której realizacja możliwa jest tylko w dniu wygaśnięcia  
+**opcja amerykańska** - dużo bardziej liberalna. Jej realizacji można dokonać w dowolnym terminie aż do dnia wygaśnięcia  


####1.1.1. Opcja call  
**Opcja call** -prawo (ale nie obowiązek) kupna określonej ilości instrumentu podstawowego po ustalonej cenie w ustalonym czasie. 

**Przykład**  
W dniu 22 października wystawiona została europejska opcja call.   
Instrumentem podstawowym jest waluta euro. Termin wygaśnięcia przypada 10 listopada bieżącego roku. Opcja wystawiona jest na 10000 euro. Cena wykonania wynosi 4,15 pln za 1 euro. Cena zakupu jednej opcji wynosi 0,06 pln w przeliczeniu na 1 euro. Oznacza to, że nabywca opcji zapłaci 600 pln za prawo kupna od wystawcy opcji 10000 euro po cenie 4,15 pln za 1 euro. Rozważmy teraz trzy sytuacje w momencie wygaśnięcia:  

W przypadku, gdzie kurs euro będzie poniżej 4,15 pln, to operacja nie zostanie wykonana, ponieważ nie ma sensu kupowanie opcji po 4,15 pln za 1 euro, jeżeli ich aktualna cena rynkowa jest niższa. W tej sytuacji posiadacz opcji straci całą sumę wydatkowaną na zakup opcji, czyli 600 pln. Możemy powiedzieć, że opcja jest out of the money.
W przypadku, gdzie kurs euro będzie powyżej 4,15 pln, to operacja zostanie wykonana, ponieważ opłaca się kupić opcję po cenie wykonania, która jest niższa od obecnej ceny rynkowej. Załóżmy, że kurs euro wynosi 4,22 pln. Łatwo policzyć , że zysk tej transakcji bez kosztów operacyjnych wyniesie 700 pln. Odejmując od tej kwoty koszty początkowe (czyli 600 pln), otrzymamy zysk netto równy 100 pln. Możemy zatem powiedzieć, że opcja jest in the money .
W przypadku, gdzie kurs euro zostanie na tym samym poziomie (tzn. 1 euro= 4,15 pln), to nie ma znaczenia czy wypłata zostanie wykonana czy nie. Wypłata w obydwu sytuacjach będzie wynosić 0. Mówimy wtedy, że opcja jest at the money.
Spójrzmy teraz na punkt widzenia sprzedającego:

W przypadku, gdzie kurs euro będzie poniżej 4,15 pln, posiadacz opcji kupna nie zdecyduje się na jej wykonanie. Pozwala to zatrzymać wystawcy opcji kupna premię i jest to maksymalny zysk jaki może on osiągnąć.
W przypadku, gdzie kurs euro będzie powyżej 4,15 pln opcja przestaje być opłacalna dla wystawcy. Jak widać ryzyko jakie ponosi wystawiający opcję jest bardzo duże. Przy wzroście ceny opcji jego straty rosną.  

Algorytmy na kalkulacje kwoty rozliczenia są następujące:


[(S-X)*m]  

gdzie:  

**S** – kurs instrumentu bazowego  

**X** – kurs wykonania opcji  

**m** - mnożnik, dla opcji na akcje określa liczbę akcji przypadających na jedną opcję (dla opcji akcyjnych notowanych na GPW zawsze wynosi 100), a dla opcji na indeks określa wartość jednego punktu indeksowego (dla opcji indeksowych notowanych na GPW zawsze wynosi 10 zł)


Zachowanie posiadacza opcji kupna w terminie wygaśnięcia na przykładzie opcji na akcje Orange Polska (OPL) z kursem wykonania 26 zł. Na jedną opcję przypada 100 sztuk akcji tej spółki.

Wariant 1 – w terminie wygaśnięcia opcji kurs akcji OPL na Giełdzie wynosi 27 zł. Nabywca opcji kupna wykona opcję, ponieważ kurs instrumentu bazowego S=27zl jest powyżej kursu wykonania opcji X=26zł
[(S – X)* m = (27zł – 26zł) * 100 akcji = 100zł]

Wariant 2) – w terminie wygaśnięcia opcji kurs akcji OPL na Giełdzie wynosi 25 zł. Nabywca opcji kupna nie wykona opcji, ponieważ kurs instrumentu bazowego (S = 25 zł) jest niższy niż kurs wykonania opcji (X = 26 zł). Kwota rozliczenia = 0





####1.1.2. Opcja put  
**Opcja put** - prawo (ale nie obowiązek) sprzedaży określonej ilości instrumentu podstawowego po ustalonej cenie w ustalonym okresie.  

**Przykład**  

W dniu 23 października wystawiona została europejska opcja put. Opcja jest wystawiona na 10000 euro. Termin wygaśnięcia opcji nastąpi 15 listopada bieżącego roku. Cena wykonania wynosi 4,02 pln za 1 euro, a cena opcji wynosi 0,03 pln w przeliczeniu na 1 euro. Posiadacz opcji zapłaci 300 pln za prawo sprzedaży wystawcy. Rozpatrzmy znów 3 sytuacje:

jeżeli w dniu wygaśnięcia kurs euro spadnie poniżej 4,02 pln, to opcja zostanie wykonana, gdyż jej posiadacz skorzysta z prawa sprzedaży euro po cenie wykonania wyższej niż cena rynkowa euro. W przypadku kursu euro wynoszącego 3,97 pln wypłata posiadacza opcji wynosi 500 pln. Dochód posiadacza opcji wynosi 200 pln.
jeżeli w dniu wygaśnięcia kurs euro będzie powyżej 4,02 pln, to opcja nie zostanie wykonana.
jeżeli kurs euro będzie równy 4,02 pln, to nie ma znaczenia czy opcja zostanie wykonana czy nie.
Spójrzmy teraz na punkt widzenia sprzedającego:

jeżeli w dniu wygaśnięcia kurs euro spadnie poniżej 4,02 pln opcja przestaje być opłacalna dla wystawcy. Im kurs euro jest niższy od ceny wykonania tym wystawca ponosi wyższą stratę.
jeżeli w dniu wygaśnięcia kurs euro będzie powyżej 4,02 pln, to wystawca zrealizuje swój maksymalny zysk, który jest równy premii.

Algorytmy na kalkulacje kwoty rozliczenia są następujące:  
  
[(X-S)*m]

gdzie:

**S** – kurs instrumentu bazowego  

**X** – kurs wykonania opcji  

**m** - mnożnik  

Zachowanie posiadacza opcji sprzedaży w terminie wygaśnięcia na przykładzie opcji na akcje Orange Polska z kursem wykonania 24 zł. Na jedną opcję przypada 100 sztuk akcji tej spółki.

Wariant 1 – w terminie wygaśnięcia opcji kurs akcji OPL na Giełdzie wynosi 22 zł. Nabywca opcji sprzedaży wykona opcję, ponieważ kurs instrumentu bazowego (S = 22 zł) jest poniżej kursu wykonania opcji (X = 24 zł).
[(X - S)* m = (24zł – 22zł) * 100 akcji = 200zł]

Wariant 2) – w terminie wygaśnięcia opcji kurs akcji OPL na Giełdzie wynosi 25 zł. Nabywca opcji sprzedaży nie wykona opcji, ponieważ kurs instrumentu bazowego (S = 25 zł) jest wyższy od kursu wykonania opcji (X = 24 zł).


###2. Opcja - wycena instrumentu  
***

#### 2.1. Wzór Blacka-Scholesa  
Są to podstawowe wzory, które zna każdy szanujący się analityk bądź ekonometryk. Służą one do wyceny optymalnej ceny opcji kupna, ewentualnie sprzedaży. Stosuje się je do opcji typu europejskiego.  

Podstawowe wartości wykorzystywane we wzorach:  
**C**- cena opcji kupna  
**P**- cena opcji sprzedaży  
**S**- aktualna cena instrumentu bazowego  
**X**- cena rozliczenia opcji  
**T**- termin wygaśnięcia opcji (w latach)  
**r**- stopa procentowa wolna od ryzyka  
$\Phi$- dystrybuanta standardowego rozkładu normalnego  
$\sigma$ - współczynnik zmienności ceny instrumentu bazowego  

#### 2.2. Wzór Blacka-Scholesa dla opcji sprzedaży  

Poniżej prezentuje wzór na wycenę opcji sprzedaży:  
  
$P={X}e^{-rT}\Phi \left ( \frac{-ln\frac{S}{X}-(r-\frac{\sigma ^{2}}{2})T}{\sigma\sqrt{T}} \right )-S\Phi\left ( \frac{-ln\frac{S}{X}-(r+\frac{\sigma ^{2}}{2})T}{\sigma\sqrt{T}} \right )$


#### 2.3. Wzór Blacka-Scholesa dla opcji kupna  

Poniżej prezentuje wzór na wycenę opcji kupna:    
  
$C={S}\Phi \left ( \frac{ln\frac{S}{X}+(r+\frac{\sigma ^{2}}{2})T}{\sigma\sqrt{T}} \right )-Xe^{-rT}\Phi\left ( \frac{ln\frac{S}{X}+(r-\frac{\sigma ^{2}}{2})T}{\sigma\sqrt{T}} \right )$

###3. Przykładowe zadania  
***

#### 3.1. Zadanie1  
Znając współczynnik zmienności ceny instrumnetu bazowego równy 0,1  
oblicz optymalną wycenę europejskiej opcji kupna dla akcji spółki NiktniekorzystazLateXa S.A.   
której aktualna cena wynosi 50 zł, cena rozliczenia to 60 zł, termin wygasniecia to 1 rok, wysokość stopy procentowej to 5%.  

$C={50}\Phi \left ( \frac{ln\frac{50}{60}+(0.05+\frac{0.1 ^{2}}{2})1}{0.1\sqrt{1}} \right )-60e^{-0.05}\Phi\left ( \frac{ln\frac{50}{60}+(0.05-\frac{0.1 ^{2}}{2})1}{0.1\sqrt{1}} \right)$

Wyliczając z powyższego wzoru, co jest trywialne więc nie będę tego umieszczał w dokumencie,  
wycena jest równa **0,23 PLN**.


#### 3.2. Zadanie2  
Znając współczynnik zmienności ceny instrumnetu bazowego równy 0,1   
oblicz optymalną wycene europejskiej opcji sprzedaży dla akcji spółki RStuditobankrut S.A.  
której aktualna cena wynosi 50 zł, cena rozliczenia to 60 zł, termin wygasniecia to 1 rok, wysokość stopy procentowej to 5%.  

$P={60}e^{-0.05}\Phi \left ( \frac{-ln\frac{50}{60}-(0.05-\frac{0.1 ^{2}}{2})T}{0.1\sqrt{1}} \right )-50\Phi\left ( \frac{-ln\frac{50}{60}-(0.05+\frac{0.1 ^{2}}{2})T}{0.1\sqrt{1}} \right )$

Ponownie wyliczając z powyższego wzoru, co jest oniegdaj znów trywialne,  
wycena wychodzi **7,31 PLN**.

###4. Przypisy  
***

W tej pracy korzystaliśmy z poniższych źródeł:  
*www.wikipedia.org*  
*www.knf.gov.pl*  
*www.jamer.pl*  
*Jajuga K., Jajuga T.; Inwestycje: instrumenty finansowe, aktywa niefinansowe, ryzyko finansowe, inżynieria finansowa; PWN, Warszawa 2014*  
*www.tu.kielce.pl/~grysa/IF3.pdf*  
*J.Hull, Kontrakty terminowe i opcje; Warszawa*  
*T. Jóźwik; Wprowadzenie do opcji giełdowych; Giełda Papierów Wartościowych w Warszawie S.A.* *www.nbp.pl*
*www.pochodne.gpw.pl/pub/pdf/1_BROSZURA_LONG_CALL.pdf*  
*www.pochodne.gpw.pl/pub/pdf/2_BROSZURA_LONG_PUT.pdf*  
*www.pochodne.gpw.pl/pub/pdf/3_BROSZURA_SHORT_CALL.pdf*
*www.pochodne.gpw.pl/pub/pdf/4_BROSZURA_SHORT_PUT.pdf*  
*www.static.gpw.pl/pub/files/PDF/foldery/GPW_Podstawy_Inwestowania_2014.pdf*  
